In [ ]:

txt= "Hi there sami"
s= txt.split()
print(s)

['Hi', 'there', 'sami']


In [ ]:
planet="earth"
diameter=12742
print('The diameter of {} is {} kilometers,'.format(planet,diameter));

The diameter of earth is 12742 kilometers,


In [1]:
Ist=[1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
a=Ist[3][1][2];
print(a)

['hello']


In [3]:
import numpy as np
array=np.zeros(10)
print("an array of 10:")
print(array)
array=np.ones(10)
print("an array of 10 ones:")
print(array)
array=np.ones(10)*5
print("an array of 10 fives:")
print(array)

an array of 10:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
an array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
an array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [4]:
import numpy as np
array=np.arange(20,34,2)
print("array of all the evan integer form 20 to 35 ")
print(array)

array of all the evan integer form 20 to 35 
[20 22 24 26 28 30 32]


In [6]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
